---
  - name: openshift-vanilla
    type: ocp
    location: agents/openshift-vanilla
    inventory: agents/openshift-vanilla
    outputs:
      kubeconfig: agents/openshift-vanilla/outputs/localhost/kubeconfig
    topic: OCP-4.4
    success_tag: ocp-vanilla-ok
    fallback_last_success: ocp-vanilla-ok

  - name: rh-cnf
    type: cnf
    location: agents/rh-cnf
    inputs:
      kubeconfig: agents/rh-cnf/kubeconfig
    topic: RH-CNF-0.1
    success_tag: ocp-vanilla-ok
    fallback_last_success: ocp-vanilla-ok
